train:
    max_iter: 10000
    display: 10
    snapshot_iter: 500
    batch_size: 64
    test_batch_size: 100
    latent_dims: 100
    log: ../outputs/mnist2usps_cogan/mnist2usps_full_cogan.log
    snapshot_prefix: ../outputs/mnist2usps_cogan/mnist2usps_full_cogan
    scale: 2.0
    bias: 0.5
    cls_weight: 10.0
    mse_weight: 0.01
    train_data_a: MNISTSAMPLE
    train_data_a_path: ../data/mnistsample
    train_data_a_size: 60000
    train_data_a_seed: 0
    train_data_a_use_train_data: True
    train_data_b: USPSSAMPLE
    train_data_b_path: ../data/uspssample
    train_data_b_size: 7438
    train_data_b_seed: 0
    train_data_b_use_train_data: True
    test_data_b: USPSSAMPLE
    test_data_b_path: ../data/uspssample
    test_data_b_size: 1860
    test_data_b_seed: 0
    test_data_b_use_train_data: False